[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.88.0",
    "pdfplumber>=0.11.7",
    "pypdf2>=3.0.1",
    "streamlit>=1.46.0",
]
